/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.cliente;

import app.modelo.Libro;
import app.modelo.LibroNoEncontradoException;
import app.negocio.GestionLibreria;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Frame Principal de nuestra Aplicación donde se implementado los 11 puntos
 * requeridos en el enunciado de la practica. Se ha utilizaod laHerramienta
 * Gráfica 'Swing' y Netbeans para ralizar los Formularios
 *
 * @author amatore
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    GestionLibreria libreria = new GestionLibreria();

    public MainFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelResTitulo = new javax.swing.JLabel();
        LabelResAutor = new javax.swing.JLabel();
        LabelResEditorial = new javax.swing.JLabel();
        LabelResISBN = new javax.swing.JLabel();
        LabelResPublicacion = new javax.swing.JLabel();
        LabelResPrecio = new javax.swing.JLabel();
        LabelResDescripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextBuscarTitulo = new javax.swing.JTextField();
        LabelBuscarTitulo = new javax.swing.JLabel();
        BotonBuscarTitulo = new javax.swing.JButton();
        LabelBuscarISBN = new javax.swing.JLabel();
        TextBuscarISBN = new javax.swing.JTextField();
        BotonBuscarISBN = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_libreria = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuFileExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenuFileAltaLibro = new javax.swing.JMenuItem();
        MenuDeleteBook = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuFileOpen = new javax.swing.JMenuItem();
        MenuHelpAbout = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio Evaluacion 1 - Master Experto JAVA [Atrium]");
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        LabelResTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelResTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelResTitulo.setText("Título");

        LabelResAutor.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LabelResAutor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelResAutor.setText("autor");

        LabelResEditorial.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LabelResEditorial.setText("editorial");

        LabelResISBN.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LabelResISBN.setText("ISBN");

        LabelResPublicacion.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LabelResPublicacion.setText("publicacion");

        LabelResPrecio.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LabelResPrecio.setText("precio");

        LabelResDescripcion.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LabelResDescripcion.setText("descripcion");
        LabelResDescripcion.setToolTipText("");
        LabelResDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Autor:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Editorial:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ISBN:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Publicación:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Descripción:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelResTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelResDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelResPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelResPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(LabelResISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelResEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelResAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelResTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelResAutor))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResEditorial)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResISBN)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResPublicacion)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LabelResPrecio))
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(LabelResDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TextBuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBuscarTituloActionPerformed(evt);
            }
        });

        LabelBuscarTitulo.setText("Título:");

        BotonBuscarTitulo.setText("Buscar");
        BotonBuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarTituloActionPerformed(evt);
            }
        });

        LabelBuscarISBN.setText("ISBN");

        BotonBuscarISBN.setText("Buscar");
        BotonBuscarISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarISBNActionPerformed(evt);
            }
        });

        jButton3.setText("Consultar Todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(204, 0, 51));
        jButton4.setText("Vaciar Libreria");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("+ Libro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("- Libro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Tabla_libreria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Editorial", "ISBN", "Publicacion", "Precio", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_libreria);
        if (Tabla_libreria.getColumnModel().getColumnCount() > 0) {
            Tabla_libreria.getColumnModel().getColumn(0).setPreferredWidth(200);
            Tabla_libreria.getColumnModel().getColumn(0).setMaxWidth(200);
            Tabla_libreria.getColumnModel().getColumn(1).setPreferredWidth(200);
            Tabla_libreria.getColumnModel().getColumn(1).setMaxWidth(200);
            Tabla_libreria.getColumnModel().getColumn(2).setPreferredWidth(100);
            Tabla_libreria.getColumnModel().getColumn(2).setMaxWidth(100);
            Tabla_libreria.getColumnModel().getColumn(3).setPreferredWidth(50);
            Tabla_libreria.getColumnModel().getColumn(3).setMaxWidth(50);
            Tabla_libreria.getColumnModel().getColumn(4).setPreferredWidth(100);
            Tabla_libreria.getColumnModel().getColumn(4).setMaxWidth(100);
            Tabla_libreria.getColumnModel().getColumn(5).setPreferredWidth(75);
            Tabla_libreria.getColumnModel().getColumn(5).setMaxWidth(75);
            Tabla_libreria.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        jButton1.setText("Nuevo Precio");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelBuscarTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BotonBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelBuscarISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextBuscarISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscarISBN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBuscarTitulo)
                    .addComponent(BotonBuscarTitulo)
                    .addComponent(LabelBuscarISBN)
                    .addComponent(TextBuscarISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarISBN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Libreria", jPanel1);

        jMenu1.setText("Archivo");

        MenuFileExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.CTRL_MASK));
        MenuFileExit.setText("Salir");
        MenuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");
        jMenu2.setEnabled(false);

        jMenu5.setText("Limipar");

        jMenuItem4.setText("Cache");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Historial de Búsqueda");
        jMenu5.add(jMenuItem5);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Libro");
        jMenu7.setEnabled(false);

        MenuFileAltaLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuFileAltaLibro.setText("Nuevo");
        jMenu7.add(MenuFileAltaLibro);

        MenuDeleteBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        MenuDeleteBook.setText("Borrar");
        MenuDeleteBook.setToolTipText("");
        jMenu7.add(MenuDeleteBook);

        jMenu9.setText("Buscar por...");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("Título");
        jMenu9.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("ISBN");
        jMenuItem3.setToolTipText("");
        jMenu9.add(jMenuItem3);

        jMenu7.add(jMenu9);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Libreria");
        jMenu8.setEnabled(false);

        jMenuItem6.setText("Consultar Todos");
        jMenu8.add(jMenuItem6);

        jMenuItem7.setText("Vaciar Libreria");
        jMenu8.add(jMenuItem7);

        jMenuBar1.add(jMenu8);

        jMenu6.setText("Ayuda");

        MenuFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        MenuFileOpen.setText("Test Conexión Base de datos");
        MenuFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileOpenActionPerformed(evt);
            }
        });
        jMenu6.add(MenuFileOpen);

        MenuHelpAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuHelpAbout.setText("Acerca de...");
        MenuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpAboutActionPerformed(evt);
            }
        });
        jMenu6.add(MenuHelpAbout);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileOpenActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("");

        if (libreria.conectar()) {
            JOptionPane.showMessageDialog(frame, "Conexión BD satisfactoria\n" + libreria.getRutaBD(), "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(frame, "Error al conectar con la BD\n" + libreria.getRutaBD(), "Error", JOptionPane.ERROR_MESSAGE);

        }

        libreria.cerrarConexion();
    }//GEN-LAST:event_MenuFileOpenActionPerformed

    private void MenuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileExitActionPerformed
        // TODO add your handling code here:

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_MenuFileExitActionPerformed

    private void MenuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHelpAboutActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        NuevoLibroFrame nuevolibro = new NuevoLibroFrame();
        nuevolibro.show();

    }//GEN-LAST:event_jButton5ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        VaciarTabla();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        RellenarTabla(this.libreria.consultarTodos());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void BotonBuscarISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarISBNActionPerformed
        // TODO add your handling code here:
        try {
            String text_isbn = TextBuscarISBN.getText();

            Libro l = libreria.consultarISBN(text_isbn);

            if (libreria.isbn_search) {
                VaciarTabla();
                ResultadoISBNLibro(l);
                ResultadoISBNTabla(l, 0);

            } else {
                throw new LibroNoEncontradoException(TextBuscarISBN.getText());
            }

        } catch (LibroNoEncontradoException e) {

            JFrame frame = new JFrame("");
            JOptionPane.showMessageDialog(frame, "No existe ningún libro con ISBN:\n" + TextBuscarISBN.getText(), "Información", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_BotonBuscarISBNActionPerformed

    private void BotonBuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarTituloActionPerformed

        try {
            VaciarTabla();
            RellenarTabla(this.libreria.consultarTitulo(TextBuscarTitulo.getText()));

            if (!libreria.encontrado) {
                throw new LibroNoEncontradoException("Libro con titulo:\n " + TextBuscarTitulo.getText() + "\nNO Encontrado");
            }
        } catch (LibroNoEncontradoException e) {

            JFrame frame = new JFrame("");
            JOptionPane.showMessageDialog(frame, "" + e.message(), "Información", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_BotonBuscarTituloActionPerformed

    private void TextBuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBuscarTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBuscarTituloActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        BorrarLibroFrame Borrarlibro = new BorrarLibroFrame();
        Borrarlibro.show();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NuevoPrecioFrame NuevoPrecio = new NuevoPrecioFrame();
        NuevoPrecio.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void RellenarTabla(List<Libro> libreria) {

        int columnas = Tabla_libreria.getColumnCount();
        int filas = Tabla_libreria.getRowCount();

        // VaciarTabla();
        System.out.println("columnaS:" + columnas + "filas:" + filas);
        Libro l;
        for (int i = 0; i < libreria.size(); i++) {

            l = libreria.get(i);

            Tabla_libreria.setValueAt(l.getTitulo(), i, 0);
            Tabla_libreria.setValueAt(l.getAutor(), i, 1);
            Tabla_libreria.setValueAt(l.getEditorial(), i, 2);
            Tabla_libreria.setValueAt(l.getIsbn(), i, 3);
            Tabla_libreria.setValueAt(l.getPublicacion(), i, 4);
            Tabla_libreria.setValueAt(l.getPrecio(), i, 5);
            Tabla_libreria.setValueAt(l.getDescripcion(), i, 6);

            System.out.println("i:" + i + "\n");

        }

    }

    public void VaciarTabla() {
        int columnas = Tabla_libreria.getColumnCount();
        int filas = Tabla_libreria.getRowCount();

        System.out.println("columnaS:" + columnas + "filas:" + filas);

        for (int i = 0; i < filas - 1; i++) {

            Tabla_libreria.setValueAt("", i, 0);
            Tabla_libreria.setValueAt("", i, 1);
            Tabla_libreria.setValueAt("", i, 2);
            Tabla_libreria.setValueAt("", i, 3);
            Tabla_libreria.setValueAt(null, i, 4);
            Tabla_libreria.setValueAt(null, i, 5);
            Tabla_libreria.setValueAt("", i, 6);

        }

    }

    public void ResultadoISBNLibro(Libro l) {

        LabelResTitulo.setText(l.getTitulo());
        LabelResAutor.setText(l.getAutor());
        LabelResEditorial.setText(l.getEditorial());
        LabelResISBN.setText(l.getIsbn());
        LabelResPublicacion.setText("" + l.getPublicacion());
        LabelResPrecio.setText(l.getPrecio() + "€");
        LabelResDescripcion.setText("<html>" + l.getDescripcion() + "<html>");

    }

    public void ResultadoISBNTabla(Libro l, int fila) {

        Tabla_libreria.setValueAt(l.getTitulo(), fila, 0);
        Tabla_libreria.setValueAt(l.getAutor(), fila, 1);
        Tabla_libreria.setValueAt(l.getEditorial(), fila, 2);
        Tabla_libreria.setValueAt(l.getIsbn(), fila, 3);
        Tabla_libreria.setValueAt(l.getPublicacion(), fila, 4);
        Tabla_libreria.setValueAt(l.getPrecio(), fila, 5);
        Tabla_libreria.setValueAt(l.getDescripcion(), fila, 6);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }

    public javax.swing.JDialog jDialog2;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonBuscarISBN;
    public javax.swing.JButton BotonBuscarTitulo;
    public javax.swing.JLabel LabelBuscarISBN;
    public javax.swing.JLabel LabelBuscarTitulo;
    public javax.swing.JLabel LabelResAutor;
    private javax.swing.JLabel LabelResDescripcion;
    private javax.swing.JLabel LabelResEditorial;
    private javax.swing.JLabel LabelResISBN;
    private javax.swing.JLabel LabelResPrecio;
    private javax.swing.JLabel LabelResPublicacion;
    public javax.swing.JLabel LabelResTitulo;
    public javax.swing.JMenuItem MenuDeleteBook;
    private javax.swing.JMenuItem MenuFileAltaLibro;
    public javax.swing.JMenuItem MenuFileExit;
    public javax.swing.JMenuItem MenuFileOpen;
    public javax.swing.JMenuItem MenuHelpAbout;
    private javax.swing.JTable Tabla_libreria;
    public javax.swing.JTextField TextBuscarISBN;
    public javax.swing.JTextField TextBuscarTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables

}
